# Site settings
title: Sarah Dionne
subtitle: Physiothérapie pédiatrique · Acupuncture · Reiki
email: info@dionne.com
description: > # ignore newlines
  Physiothérapie pédiatrique · Acupuncture · Reiki
logo: /assets/img/logo.png

theme: jekyll-theme-minimal
